-- =============================================================================
-- Migration: 007_seed_initial_data.sql
-- Description: Seed initial data for development environment
-- =============================================================================

-- Insert development company
INSERT INTO companies (
    id,
    name,
    tax_id,
    plan_type,
    settings,
    is_active
) VALUES (
    '00000000-0000-0000-0000-000000000001'::uuid,
    'Acme Property Management',
    'TAX-12345-ACME',
    'enterprise',
    '{"currency": "USD", "timezone": "America/Argentina/Buenos_Aires", "language": "es"}'::jsonb,
    true
) ON CONFLICT (id) DO NOTHING;

-- Insert super admin user
-- Password: Admin123! (hashed with bcrypt - this is a placeholder, real hash should be generated by app)
INSERT INTO users (
    id,
    email,
    password_hash,
    first_name,
    last_name,
    phone,
    role,
    is_active,
    is_email_verified,
    email_verified_at
) VALUES (
    '00000000-0000-0000-0000-000000000002'::uuid,
    'admin@rent.local',
    '$2b$10$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', -- Placeholder hash
    'System',
    'Administrator',
    '+1234567890',
    'admin',
    true,
    true,
    CURRENT_TIMESTAMP
) ON CONFLICT (email) DO NOTHING;

-- Insert admin record for super admin
INSERT INTO admins (
    user_id,
    is_super_admin,
    department,
    title
) VALUES (
    '00000000-0000-0000-0000-000000000002'::uuid,
    true,
    'IT',
    'System Administrator'
) ON CONFLICT (user_id) DO NOTHING;

-- =========================================================================
-- Sample data for development/testing
-- =========================================================================

-- Sample Owner User
INSERT INTO users (
    id,
    email,
    password_hash,
    first_name,
    last_name,
    phone,
    role,
    is_active,
    is_email_verified,
    email_verified_at
) VALUES (
    '00000000-0000-0000-0000-000000000003'::uuid,
    'owner@example.com',
    '$2b$10$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'John',
    'Doe',
    '+1234567891',
    'owner',
    true,
    true,
    CURRENT_TIMESTAMP
) ON CONFLICT (email) DO NOTHING;

INSERT INTO owners (
    user_id,
    tax_id,
    bank_account,
    bank_name,
    preferred_payment_method
) VALUES (
    '00000000-0000-0000-0000-000000000003'::uuid,
    'TAX-OWNER-001',
    '1234567890',
    'Bank of America',
    'bank_transfer'
) ON CONFLICT (user_id) DO NOTHING;

-- Sample Tenant User
INSERT INTO users (
    id,
    email,
    password_hash,
    first_name,
    last_name,
    phone,
    role,
    is_active,
    is_email_verified,
    email_verified_at
) VALUES (
    '00000000-0000-0000-0000-000000000004'::uuid,
    'tenant@example.com',
    '$2b$10$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'Jane',
    'Smith',
    '+1234567892',
    'tenant',
    true,
    true,
    CURRENT_TIMESTAMP
) ON CONFLICT (email) DO NOTHING;

INSERT INTO tenants (
    user_id,
    dni,
    emergency_contact_name,
    emergency_contact_phone,
    employment_status,
    employer_name,
    monthly_income,
    number_of_occupants,
    has_pets
) VALUES (
    '00000000-0000-0000-0000-000000000004'::uuid,
    'DNI-12345678',
    'Emergency Contact',
    '+1234567899',
    'employed',
    'Tech Corp',
    5000.00,
    2,
    false
) ON CONFLICT (user_id) DO NOTHING;

-- Sample Staff User
INSERT INTO users (
    id,
    email,
    password_hash,
    first_name,
    last_name,
    phone,
    role,
    is_active,
    is_email_verified,
    email_verified_at
) VALUES (
    '00000000-0000-0000-0000-000000000005'::uuid,
    'staff@example.com',
    '$2b$10$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'Bob',
    'Martinez',
    '+1234567893',
    'staff',
    true,
    true,
    CURRENT_TIMESTAMP
) ON CONFLICT (email) DO NOTHING;

INSERT INTO staff (
    user_id,
    company_id,
    specialization,
    hourly_rate,
    is_available,
    certifications,
    languages
) VALUES (
    '00000000-0000-0000-0000-000000000005'::uuid,
    '00000000-0000-0000-0000-000000000001'::uuid,
    'plumbing',
    50.00,
    true,
    ARRAY['Licensed Plumber', 'HVAC Certified'],
    ARRAY['English', 'Spanish']
) ON CONFLICT (user_id) DO NOTHING;

-- Log completion
DO $$
BEGIN
    RAISE NOTICE '✓ Initial seed data inserted successfully';
    RAISE NOTICE '  - Company: Acme Property Management';
    RAISE NOTICE '  - Super Admin: admin@rent.local';
    RAISE NOTICE '  - Sample Owner: owner@example.com';
    RAISE NOTICE '  - Sample Tenant: tenant@example.com';
    RAISE NOTICE '  - Sample Staff: staff@example.com';
    RAISE NOTICE '';
    RAISE NOTICE 'NOTE: All users have placeholder password hashes.';
    RAISE NOTICE '      These must be replaced with real bcrypt hashes in production.';
    RAISE NOTICE '      Use a password hashing utility or backend service to generate proper hashes.';
END $$;
