apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rent
resources:
- namespace.yaml
- storage.yaml
- access.yaml
- config.yaml
- postgres.yaml
- apps.yaml
- cronjobs.yaml
patches:
- target:
    kind: CronJob
  path: wait-for-database.yaml
